targets:
  $default:
    builders:
      json_serializable:
        options:
          explicit_to_json: true
          field_rename: snake
global_options:
  freezed:
    runs_before:
      - json_serializable
      - retrofit_generator
  json_serializable:
    runs_before:
      - retrofit_generator