name: fakelab_records_webapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  js: ^0.7.1
  http: ^1.3.0
  dio: ^5.8.0+1
  get_it: ^8.0.3
  logger: ^2.5.0
  freezed: ^2.5.8
  retrofit: ^4.4.2
  injectable: ^2.5.0
  flutter_svg: ^2.0.17
  flutter_dotenv: ^5.2.1
  cupertino_icons: ^1.0.8
  json_annotation: ^4.9.0
  dio_smart_retry: ^7.0.1
  freezed_annotation: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.15
  json_serializable: ^6.9.4
  retrofit_generator: ^9.1.9
  injectable_generator: ^2.7.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
